### ISSUE TITLE
Make bundle compatible with Symfony 3

### ISSUE THREAD

**Issue by asjustas** [Aureja/JobQueueBundle#10]
In symfony 3 forms has changed, now loading form by alias doesn`t work, you need to provide class. We need to decide how connect job type with form. I tried to fix that https://github.com/asjustas/JobQueueBundle/commit/133001ab968b68e7e247ece949a5b55c031e9e92

**Comment by asjustas** [comment]
Pull request https://github.com/Aureja/JobQueueBundle/pull/11

**Comment by tadcka** [comment]
Resolve #12
